"""initial migration

Revision ID: b0cbd9d469c9
Revises: 
Create Date: 2026-01-26 14:36:48.987495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cbd9d469c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_logs', sa.Column('action', sa.String(), nullable=False))
    op.add_column('agent_logs', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('agent_logs', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_logs', 'tasks', ['task_id'], ['id'])
    op.drop_column('agent_logs', 'output_data')
    op.drop_column('agent_logs', 'input_data')
    op.add_column('projects', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.drop_column('projects', 'status')
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'description')
    op.add_column('projects', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.drop_column('projects', 'user_id')
    op.add_column('agent_logs', sa.Column('input_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('agent_logs', sa.Column('output_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agent_logs', type_='foreignkey')
    op.drop_column('agent_logs', 'task_id')
    op.drop_column('agent_logs', 'timestamp')
    op.drop_column('agent_logs', 'action')
    # ### end Alembic commands ###
